### ISSUE TITLE
Overhaul ReadMe Files

### ISSUE THREAD

**Issue by Aevyz** [lupuleasa-core/Dota2-TheCore-Config-Engine#156]
It's become quite clear that the ReadMe file is outdated and needs to be updated to accommodate the Spring Cleaning changes. 

Specifically this line:

> Remove all in-game keybinds. Do this by left clicking on a bind, then click the X that appears. If you want to be safe, press F12 in-game to save a screenshot of your binds so you don't forget them if you ever wish to go back and uninstall my engine.

is no longer true.
#154 Sorry refrenced the wrong thread

---
# Things to be changed
- Quick Attack in settings should be ticked  (thanks @MauroFD )
- `bind keys based on keyboard position` needs to be checked. Additional benefit: German Config is now nullified, there is no need for it. 
- Note on how to remap " ` " key if required
- And probably half a billion other small things...

**Comment by dodekeract** [comment]
@AetherV Could you explain what isn't true in that line and how it's related to #137?

**Comment by AetherV** [comment]
I refrenced the wrong thread *facepalms*

**Comment by dodekeract** [comment]
Also I suggest to move the "troubleshooting" part to a TROUBLESHOOTING.md, like other repos do it and link to that file in the README.md

**Comment by loopuleasa** [comment]
I can add some more readme points, just add in this thread what is needed.

**Comment by AetherV** [comment]
Oh yeah @loopuleasa, quality of life improvement for windows users: Shorten File Names. Windows has a file path limit of 260 ([cached because the site ain't work in Chrome](https://webcache.googleusercontent.com/search?q=cache:KPMjH4xs0ZAJ:https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v%3Dvs.85).aspx+&cd=1&hl=en&ct=clnk&gl=de)). The Standard `C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\cfg` install location plus `Loopuleasa's Super Compact QWERTG-DFXCV layout (ALT,SPACE mods).zip\Loopuleasa's Super Compact QWERTG-DFXCV layout (ALT,SPACE mods)\dota2_gameplay_mode\aliases\` gets you way further than 260 characters, making extraction process a bit fuzzy for windows users at times.

**Comment by dodekeract** [comment]
When you guys are about to change the name, why not just call it "the core" and be done with it? I mean, no offense but this project is AFAIK not really used as an engine, but as a finished configuration everybody can download.

**Comment by AetherV** [comment]
Yeah that would shorten the name by quite a bit.

Issue was found in #157 

Reproduction:

1. Be on Windows (I am on 10)
2. Try Extracting the Config in `C:\Program Files (x86)\Steam\steamapps\common\dota 2 beta\game\dota\cfg`
3. Windows Default Extractor will throw an error

![image](https://cloud.githubusercontent.com/assets/17731961/15471399/12751514-20f6-11e6-8d7f-8b9321627f02.png)

Note: 7-Zip does not throw an error, however not all users shall be running 7-zip

**Comment by dodekeract** [comment]
@AetherV My condolences for having to use W10.

**Comment by AetherV** [comment]
Well I had the option of sticking with 7 or DX12. Planning on dual booting with Mint soon so I don't have to use a VM all the time, but W10 throws its usual fits about dual booting.

**Comment by dodekeract** [comment]
@AetherV yeah, in my experience dual booting becomes increasingly hard/weird with each release.

**Comment by AetherV** [comment]
I loved the days of Wubi. Was so simple to dualboot, just a simple exe file. Meanwhile now I got to mess with my UEFI, it's almost easier to get OSX running then a dual boot right now.

**Comment by AetherV** [comment]
@loopuleasa, took some time to make an installer for the config (only works on Windows though). Probably got a couple of bugs, but seems to be working on my end. 

Github: https://github.com/AetherV/Dota2-Config-Installer
Download: https://github.com/AetherV/Dota2-Config-Installer/blob/master/Compiled/Dota2%20Config%20Installer%20v1.jar?raw=true

Might try to adapt the code to accept files from @dodekeract 's Manta, but this might be a step in automating most common install mistakes. It also does not remove the original configs, since it adds separate folders. 
![image](https://cloud.githubusercontent.com/assets/17731961/15482439/e4d378a0-212f-11e6-91f4-d76788db5282.png)

**Comment by dodekeract** [comment]
@AetherV I also thought about doing something like this. Haven't made any real progress though. In case you feel like implementing Manta support on that, just mention me and I'll try to help.

**Comment by AetherV** [comment]
I'll give it a shot tomorrow, should not be that hard to adapt the code. Most of it is still there. The only problem is that it is currently hard coded for windows file structure. Gotta check the differences in file structure between Linux and OSX. I'll leave a note somewhere on your project when I run into a snag.

**Comment by dodekeract** [comment]
@AetherV [this](https://github.com/dodekeract/manta-config-engine/blob/master/source/cli.js#L18-L25) might help you adapting it for other operating systems.
